{% set version = "2.0.0" %}

package:
  name: django-admin-shortcuts
  version: {{ version }}

source:
  fn: django-admin-shortcuts-{{ version }}.tar.gz
  url: https://github.com/alesdotio/django-admin-shortcuts/archive/{{ version }}.tar.gz
  sha256: 4f7307bd3c804ba417bf0eb19cd4223b769dc1f78ab8651270d7741e3d2fd341

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - django >=1.2
  run:
    - python
    - django >=1.2

test:
  imports:
    - admin_shortcuts
    - admin_shortcuts.templatetags

about:
  home: https://github.com/alesdotio/django-admin-shortcuts
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Add simple and pretty shortcuts to the django admin homepage.'

extra:
  recipe-maintainers:
    - ocefpaf
