{% set version = "2.1.0" %}

package:
  name: django-admin-shortcuts
  version: {{ version }}

source:
  url: https://github.com/alesdotio/django-admin-shortcuts/archive/{{ version }}.tar.gz
  sha256: 84bd177e99b0cd003406eb53f2befb4ed9d0823d1871cc48694312bdef352203

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - django >=1.2
  run:
    - python
    - django >=1.2

test:
  imports:
    - admin_shortcuts
    - admin_shortcuts.templatetags

about:
  home: https://github.com/alesdotio/django-admin-shortcuts
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Add simple and pretty shortcuts to the django admin homepage.'

extra:
  recipe-maintainers:
    - ocefpaf
