{% set name = "django-admin-shortcuts" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-admin-shortcuts-{{ version }}.tar.gz
  sha256: 0e33671e312298372f7d9e98dd4f660ea73c8afb214588bb08307726157d989e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.0

test:
  imports:
    - admin_shortcuts
    - admin_shortcuts.templatetags
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alesdotio/django-admin-shortcuts
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Add simple and pretty shortcuts to the django admin homepage.'

extra:
  recipe-maintainers:
    - ocefpaf
