{% set name = "django-admin-shortcuts" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-admin-shortcuts-{{ version }}.tar.gz
  sha256: 2a5eecb382b27c6d0c36057bcbcd7dd7d0bf1e6f92006cf723ef049fc999585b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - django >=5.0

test:
  imports:
    - admin_shortcuts
    - admin_shortcuts.templatetags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alesdotio/django-admin-shortcuts
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Add simple and pretty shortcuts to the django admin homepage.'

extra:
  recipe-maintainers:
    - ocefpaf
