travis:
  secure:
    BINSTAR_TOKEN: pXC1HgNiTWm7G3yaTpSnwcNl0E7t7mrNfJDdM79nGJRkLh3PvSUnnhhhT8vfMmLINIslPUGHNUbClXsZtqxgrnvIsUSRTD0VC355QZQViTFRFpxYbd6ecOLlfa49NMV5gUr7KZUpYw3lDdnTSPBolKZxr5QPKNF7hExoKPvLnYslXQz/Ay8BVCuw+Nt3SLpZlFCeOU6M5eoteZFR0TX9rmIm+4vcIsjYGXzXtHMpGo4nYLDtdbaC80w9oabYJV5VXqF+YwdFeXyOtp9l04wGXy1yx9+xLZZPYvJifinyg+tr9Y6WnKvCDWmSwXWPfhaBQGNfvnF6z2ODOjWBIttuU6GdOfU0i17QAh9h46ocH2n+wHWmjbYUkpw7yQQjcO2+3Sv6bGrexEjpBb/5ubhY2d4IeR+3nTqk7j4rFwnTAMbzVXWv95lFzHYC9UYaqsifT7VR2yIxi3ymJWGRVkAEuz7fOobR5G2p/qXdjmFchS/xO/zccr1k08pME6CuwTsVUjMgXQQrSHHXlNsOn76BcwLmOOFjgkGtLSXgfDPAqG7FgIDaLh1tLRXbcNN63PQwIFtDJZlbaFOmV9eVjeMuzJPXFdQqhAscpZ2Neqt8JkCiLw/PXjj89/XVXccExDt/KCi3l0XBzwrirV1YV95rJXDsygdiPDZxOPVm9OjilSA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
