travis:
  secure:
    BINSTAR_TOKEN: J2l3/3Fq6PvGKF+PkcYt1aE19Yi8TDmGXmi2JeXgugp0sYf2EisTA6ovck6yP3HR0nhWTwjXqZXTouopNBxCOfNZgsRkOGelZ/S7sSd+DF3iyujEwM9rKGm2tNTCEb2Mwtmsf8AwHpfx+od8fqM7eoLZVB/NclqGlTWws6qBD8cBDyNAQL/NOCotrf56zHyY8hXiEi+RYU/oG4SCPTrE8xWLRjoF36KxlfEvjIBLF2uVlqkibzA5PMHRRl6p0nKCTaTCUilwLSXytYu+P4mP+SolLJmyV/fXmlCxR6ItQvJeoWd/qi/UjCCMBxYWrDI1/UtjhUysDqYXrhe1aG6xEJrQjbzfdg6ebFyUqAkv/9NUrsCiQZjKGmMzf3TxJmxqjyLeBX9I9Lptj+9lBsswrlm5CLWdAsAoCXWfXQnTxbsFj+h4VnvFqKrox5wxsUskyfCWmSfFB7Si+DGQGsLExEv2N3SM+gmCFNXHuGgQwL8FrQSR1fuFeZOyy12kIAZtA+VSAh+CS2lWDEhUQ6sQm5n5Oi57w9wS4Nf2+/06/+PbnKoODMe+2kIIiun/+quZ4bpkYa3Y70odfy9YMmHZ1sPaH7H0en8zUzZ56UGauTyZABbgucIUM6IHuTimWHZ/2UnUY13B29J1YC9xfert8EXmLU0VbyE9hfxjIPFnZP4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
